import enum

class Rhythm(enum.Enum):
    TWO_HUNDRED_FIFTY_SIXTH = 1
    ONE_HUNDRED_TWENTY_EIGHTH = 2
    SIXTY_FOURTH = 4
    THIRTY_SECONDTH = 8
    SIXTEENTH = 16
    EIGHTH = 32
    QUARTER = 64
    HALF = 128
    WHOLE = 256